Repository openshift-knative/kn-plugin-event, pull requests merged in 2022-04, with the labels that each got.

#141 Ensure binaries are run by unknown UID
  openshift/ci-operator/images/kn-event-sender/Dockerfile
  openshift/ci-operator/test-images/eventshub/Dockerfile
  openshift/ci-operator/test-images/wathola-forwarder/Dockerfile
Labels: lgtm, approved

#24 :robot: Synchronize branch `release-1.1` to `upstream/release-1.1`
  pkg/cli/ics/constants.go
  pkg/sender/in_cluster.go
Labels: kind/sync-fork-to-upstream, lgtm, approved

#86 :robot: Synchronize branch `release-0.26` to `upstream/release-0.26`
  pkg/cli/ics/constants.go
  pkg/sender/in_cluster.go
Labels: kind/sync-fork-to-upstream, lgtm, approved

#146 Fixing the Golangci-lint on Go 1.18 errors
  .github/workflows/golangci-lint.yaml
Labels: lgtm, approved

#152 :robot: Synchronize branch `release-0.26` to `upstream/release-0.26`
  pkg/cli/ics/constants.go
  pkg/sender/in_cluster.go
Labels: kind/sync-fork-to-upstream
