Repository openshift-knative/kn-plugin-event, pull requests merged in 2024-11, with the labels that each got.

#546 [release-1.15] :bug: Remove -mod=vendor from GOFLAGS
  openshift/e2e-tests.sh
Labels: kind/bug, lgtm, approved

#544 [release-1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/components/imagerepositories/kn-plugin-event-sender-115.yaml
  .konflux/applications/serverless-operator-135/components/imagerepositories/kn-plugin-event-test-eventshub-115.yaml
  .konflux/applications/serverless-operator-135/components/imagerepositories/kn-plugin-event-test-wathola-forwarder-115.yaml
  .konflux/applications/serverless-operator-135/components/kn-plugin-event-sender-115.yaml
  .konflux/applications/serverless-operator-135/components/kn-plugin-event-test-eventshub-115.yaml
  .konflux/applications/serverless-operator-135/components/kn-plugin-event-test-wathola-forwarder-115.yaml
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-event-sender-115-pull-request.yaml
  .tekton/kn-plugin-event-sender-115-push.yaml
  .tekton/kn-plugin-event-test-eventshub-115-pull-request.yaml
  .tekton/kn-plugin-event-test-eventshub-115-push.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-115-pull-request.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-115-push.yaml
Labels: lgtm, approved

#554 [release-1.15] :bug: Use patch level version in go.mod files
  build/go.mod
  go.mod
  go.work
Labels: approved

#557 [release-1.16] :bug: Default the Wathola home to "/" on Openshift
  openshift/e2e-tests.sh
Labels: kind/bug, lgtm, approved

#545 [release-1.16] Add Konflux configurations
  .konflux/applications/serverless-operator-136/components/imagerepositories/kn-plugin-event-sender-116.yaml
  .konflux/applications/serverless-operator-136/components/imagerepositories/kn-plugin-event-test-eventshub-116.yaml
  .konflux/applications/serverless-operator-136/components/imagerepositories/kn-plugin-event-test-wathola-forwarder-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-sender-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-test-eventshub-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-test-wathola-forwarder-116.yaml
  .konflux/applications/serverless-operator-136/serverless-operator-136.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-event-sender-116-pull-request.yaml
  .tekton/kn-plugin-event-sender-116-push.yaml
  .tekton/kn-plugin-event-test-eventshub-116-pull-request.yaml
  .tekton/kn-plugin-event-test-eventshub-116-push.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-116-pull-request.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-116-push.yaml
Labels: lgtm, approved

#568 :bug: Restore GOFLAGS to default (empty) on all Openshift related runs
  Makefile
  openshift/e2e-tests.sh
Labels: kind/bug, lgtm, approved

#577 :bug: Set GOPATH to avoid permission denied errors
  Makefile
Labels: kind/bug, lgtm, approved

#578 [release-1.16] Set GOPATH to avoid permission denied errors
  Makefile
Labels: kind/bug, lgtm, approved

#583 [release-1.15] :broom: Update the Dockerfile
  Makefile
  openshift/ci-operator/images/kn-event-sender/Dockerfile
Labels: lgtm, approved

#588 [release-1.16] Add Konflux configurations
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-sender-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-test-eventshub-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-event-test-wathola-forwarder-116.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
Labels: lgtm, approved
