Repository openshift-knative/kn-plugin-event, pull requests merged in 2024-05, with the labels that each got.

#389 :bug: Align to knative-extensions/kn-plugin-event#345
  build/overrides/test-images.go
Labels: lgtm, approved

#388 :robot: Synchronize branch `release-1.11` to `upstream/release-1.11`
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: kind/sync-fork-to-upstream, lgtm

#397 [release-1.11] :bug: Include e2e script from vendor dir
  openshift/e2e-tests.sh
Labels: kind/bug, lgtm, approved

#401 SRVCLI-401: :broom: Makefile for auto-discover of tests
  Makefile
Labels: lgtm, approved, kind/cleanup, jira/valid-reference
