Repository openshift-knative/kn-plugin-event, pull requests merged in 2024-06, with the labels that each got.

#425 :broom: Vendorless test images
  .github/workflows/images/test/eventshub/Containerfile
  .github/workflows/images/test/wathola-forwarder/Containerfile
Labels: lgtm, approved

#442 [release-1.14] :broom: o-k/hack naming convention for images
  openshift/e2e-tests.sh
  test/e2e/openshift_ci_resolver.go
Labels: lgtm, approved, kind/cleanup

#457 :robot: Synchronize branch `release-1.14` to `upstream/release-1.14`
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: kind/sync-fork-to-upstream
