Repository openshift-knative/kn-plugin-event, pull requests merged in 2025-02, with the labels that each got.

#645 [release-1.16] Bump golang.org/x/net to 0.34.0
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved

#677 [release-1.15] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: lgtm, approved, needs-ok-to-test

#672 [release-1.17] Update Konflux configurations
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-sender-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-test-eventshub-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-test-wathola-forwarder-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-sender-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-eventshub-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-wathola-forwarder-117.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-event-sender-117-pull-request.yaml
  .tekton/kn-plugin-event-sender-117-push.yaml
  .tekton/kn-plugin-event-test-eventshub-117-pull-request.yaml
  .tekton/kn-plugin-event-test-eventshub-117-push.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-117-pull-request.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-117-push.yaml
Labels: lgtm, needs-ok-to-test

#690 [release-1.15] Update Konflux configurations
  .tekton/kn-plugin-event-sender-115-pull-request.yaml
  .tekton/kn-plugin-event-sender-115-push.yaml
  .tekton/kn-plugin-event-test-eventshub-115-pull-request.yaml
  .tekton/kn-plugin-event-test-eventshub-115-push.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-115-pull-request.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-115-push.yaml
Labels: lgtm, approved, needs-ok-to-test

#713 :scroll: Reconfigure the repo sync
  .deviate.yaml
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/images/kn-event-sender/Dockerfile
  openshift/go.mod
  openshift/go.sum
  openshift/release/update-to-head.sh
  openshift/tools.go
Labels: kind/enhancement, lgtm, approved

#696 [release-1.15] Update Konflux configurations
  renovate.json
Labels: lgtm, approved, needs-ok-to-test

#736 [release-1.17] Update Konflux configurations
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-kn-event-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-sender-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-test-eventshub-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-event-test-wathola-forwarder-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-kn-event-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-sender-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-eventshub-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-wathola-forwarder-117.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-event-kn-event-117-pull-request.yaml
  .tekton/kn-plugin-event-kn-event-117-push.yaml
  .tekton/kn-plugin-event-sender-117-pull-request.yaml
  .tekton/kn-plugin-event-sender-117-push.yaml
  .tekton/kn-plugin-event-test-eventshub-117-pull-request.yaml
  .tekton/kn-plugin-event-test-eventshub-117-push.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-117-pull-request.yaml
  .tekton/kn-plugin-event-test-wathola-forwarder-117-push.yaml
  renovate.json
Labels: lgtm, approved, ok-to-test

#737 :lady_beetle: Use main to always use latest, despite tags
  openshift/release/update-to-head.sh
Labels: kind/bug, lgtm, approved
