Repository openshift-knative/kn-plugin-event, pull requests merged in 2025-05, with the labels that each got.

#865 Update OWNERS
  OWNERS
Labels: approved

#866 [main] Update dependabot configurations
  renovate.json
Labels: lgtm

#825 :gift: [SRVCLI-407] Reuse test images
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-eventshub-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-event-test-wathola-forwarder-117.yaml
  openshift/ci-operator/test-images/eventshub/Dockerfile
  openshift/ci-operator/test-images/wathola-forwarder/Dockerfile
  openshift/e2e-tests.sh
  test/e2e/openshift_ci_resolver.go
Labels: kind/enhancement, lgtm, approved

#875 Update OWNERS
  OWNERS
Labels: approved

#838 [release-v1.16] Bump golang-jwt to v4.5.2
  go.mod
  go.sum
Labels: lgtm, approved
